---
- name: step check | 发布文件是否存在。
  shell: "ls {{ deploy_service_file }}"
  connection: local
  become: no
  register: deploy_service_file_stats
  changed_when: false
  failed_when: deploy_service_file_stats.stdout_lines[0] == "" or deploy_service_file == ""

- name: step check | 服务家目录如果不存在则创建
  file: path={{ service_work_path }} owner={{ deploy_service_user }} state=directory

- name: step check | 代码存储&supervisord配置文件目录如果不存在则创建
  file: path={{ item }} state=directory
  with_items:
    - "{{ code_online_path }}"
    - "{{ code_previous_path }}"
    - "{{ code_history_path }}"
